config/routes.rb
Rails.application.routes.draw do
  resources :links

   root 'links#index'
   
   get 'review', to: 'links#review'

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :string
#  comment    :text
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  extras     :integer
#  status     :string
#

class Link < ActiveRecord::Base
    
    validates_presence_of :name, :url
    
    has_many :evaluations, dependent: :delete_all
    has_many :courses,  through: :evaluations
    
    #after_create :process_new_link
    #before_save :validates_url
    
    private
    
    def validates_url
        # parts = self.url.split('/')
        # if parts.count == 5 and parts.last != 'achievements'
        #     self.url = self.url + '/achievements' if self.url[-1] != '/'
        #     self.url = self.url + 'achievements' if self.url[-1] == '/'
        # end
    end
    
    def process_new_link
       scraper = ScraperCodeacademy.new(self.url)
       
       self.score = scraper.score
       puts "The score isss: #{self.score}"
       self.save!
    end
    
    
end

app/controllers/links_controller.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :string
#  comment    :text
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  extras     :integer
#  status     :string
#

class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    #generate
    @links = Link.includes(:courses).all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end
  
  def review
    Link.destroy_all
    generate
    #sleep 2
    @links = Link.includes(:courses).all
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:name, :url, :comment)
    end
    
    # l.evaluations.joins(:courses)
    # l.evaluations.joins(:courses).where(courses: { name: 'HTML & CSS' }).references(:courses)
    
    def generate
      scraper = ScraperCodeacademy.new
      html = Course.find_by(name: 'HTML & CSS')
      js = Course.find_by(name: 'JavaScript')
      jquery = Course.find_by(name: 'jQuery')
      php = Course.find_by(name: 'PHP')
      ruby = Course.find_by(name: 'Ruby')
      makeWebsite = Course.find_by(name: 'Make an Interactive Website')
      #get_links_test.each do |uri|
      ScraperEva.get_students_links.each do |url|
        #sleep 1
        begin
          scraper.analyse_account(url)
          link = Link.new(name: scraper.name, score: scraper.score, url: url)
          link.save!
        rescue Exception => ex
          flash[:error] = "#{ex}"
          Link.new(name: 'Desconocido',score: 0, url: url, comment: 'Error al analizar el enlace').save!
        end
        begin
          html.evaluations.create(submited: true, completed_at: scraper.html_completed_at, :link => link) if scraper.html_completed?
          js.evaluations.create(submited: true, completed_at: scraper.javascript_completed_at, :link => link) if scraper.javascript_completed?
          jquery.evaluations.create(submited: true, completed_at: scraper.jquery_completed_at, :link => link) if scraper.jquery_completed?
          php.evaluations.create(submited: true, completed_at: scraper.php_completed_at, :link => link) if scraper.php_completed?
          ruby.evaluations.create(submited: true, completed_at: scraper.ruby_completed_at, :link => link) if scraper.ruby_completed?
          makeWebsite.evaluations.create(submited: true, completed_at: scraper.last_completed_at, :link => link) if scraper.last_completed?
        rescue Exception => ex
          flash[:error] = "#{ex.error}"
        end
      end
    end
    
    def get_links_test
      ["https://www.codecademy.com/carloslrubi", "https://www.codecademy.com/es/pyJumper01856","https://www.codecademy.com/es/Francesc301"]
      #["https://www.codecademy.com/carloslrubi", "https://www.codecademy.com/es/pyJumper01856", "https://www.codecademy.com/es/alex10l", "https://www.codecademy.com/CarlosRamirez97", "https://www.codecademy.com/AlejandroMeneses02", "https://www.codecademy.com/Fultie", "https://www.codecademy.com/Alondraptr", "https://www.codecademy.com/bitSolver58281", "https://www.codecademy.com/diomel", "https://www.codecademy.com/es/LetyTellez", "https://www.codecademy.com/Cisko97", "https://www.codecademy.com/es/deathstroke14", "https://www.codecademy.com/coreMaster32397", "https://www.codecademy.com/es/MeylingMendozaMejia", "https://www.codecademy.com/es/teraSlayer04129", "https://www.codecademy.com/es/noheliagm", "https://www.codecademy.com/Malvov", "https://www.codecademy.com/Izabard", "https://www.codecademy.com/es/RocioLG", "https://www.codecademy.com/es/systemJumper65177", "https://www.codecademy.com/es/dprado", "https://www.codecademy.com/es/dprado10", "https://www.codecademy.com/ximenasilvaquintero", "https://www.codecademy.com/sekainoshihaisha", "https://www.codecademy.com/es/YosselinContreras", "https://www.codecademy.com/es/arrayAce49898", "https://www.codecademy.com/es/JasonCoreaBravo", "https://www.codecademy.com/es/boardAce72051", "https://www.codecademy.com/BleeperCat", "https://www.codecademy.com/es/Zaiyan97x", "https://www.codecademy.com/es/Francesc301", "https://www.codecademy.com/jaelgoco", "https://www.codecademy.com/users", "https://www.codecademy.com/es/JoshuaLeviAn", "https://www.codecademy.com/es/Israelmercadopatio", "https://www.codecademy.com/SuperNovaP", "https://www.codecademy.com/Garchibulin", "https://www.codecademy.com/es/CarmenMorales"]
    end
end

app/helpers/links_helper.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :string
#  comment    :text
#  score      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  extras     :integer
#  status     :string
#

module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<tr>
    <td><%= link_counter + 1 %></td>
    <td><%= link.name %></td>
    <td><%= link.url %></td>
    <td><%= content_tag(:span, '',{:class => link.evaluations.html.first.exceeded_deadline? ? 'glyphicon glyphicon-ok deadline' : 'glyphicon glyphicon-ok',  title: "Completed on #{link.evaluations.html.first.completed_at.strftime("%b %d,%Y")}"}) if link.evaluations.html.count > 0  %></td>
    <td><%= content_tag(:span, '',{:class => link.evaluations.js.first.exceeded_deadline? ? 'glyphicon glyphicon-ok deadline' : 'glyphicon glyphicon-ok',  title: "Completed on #{link.evaluations.js.first.completed_at.strftime("%b %d,%Y")}"}) if link.evaluations.js.count > 0  %></td>
    <td><%= content_tag(:span, '',{:class => link.evaluations.jquery.first.exceeded_deadline? ? 'glyphicon glyphicon-ok deadline' : 'glyphicon glyphicon-ok',  title: "Completed on #{link.evaluations.jquery.first.completed_at.strftime("%b %d,%Y")}"}) if link.evaluations.jquery.count > 0 %></td>
    <td><%= content_tag(:span, '',{:class => link.evaluations.php.first.exceeded_deadline? ? 'glyphicon glyphicon-ok deadline' : 'glyphicon glyphicon-ok',  title: "Completed on #{link.evaluations.php.first.completed_at.strftime("%b %d,%Y")}"}) if link.evaluations.php.count > 0 %></td>
    <td><%= content_tag(:span, '',{:class => link.evaluations.makewebsite.first.exceeded_deadline? ? 'glyphicon glyphicon-ok deadline' : 'glyphicon glyphicon-ok',  title: "Completed on #{link.evaluations.makewebsite.first.completed_at.strftime("%b %d,%Y")}" }) if link.evaluations.makewebsite.count > 0 %></td>
    <td><%= content_tag(:span, '',{:class => link.evaluations.ruby.first.exceeded_deadline? ? 'glyphicon glyphicon-ok deadline' : 'glyphicon glyphicon-ok',  title: "Completed on #{link.evaluations.ruby.first.completed_at.strftime("%b %d,%Y")}"}) if link.evaluations.ruby.count > 0 %></td>
    <td><%= link.evaluations.map(&:score).sum %></td>
    <td><%= link.comment %></td>
    <!--<td><%= link.extras %></td>-->
        <!--<td><%= link_to 'Show', link, :class => 'btn btn-primary' %></td>-->
        <!--<td><%= link_to 'Edit', edit_link_path(link) %></td>-->
        <!--<td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
</tr>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Listing Codecademy Courses Accounts <% link_to 'Review', review_path, :id => 'review', :class => 'btn btn-primary', remote: true %></h1>
  <% if Link.count > 0 %>
  <span>Deadline for all courses: <%= Course.first.deadline.strftime("%b %d,%Y") %> - Last review <%= time_ago_in_words(Link.last.created_at) %></span>
  <% end %>
  <table class='table table-hover table-bordered'>
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Url</th>
      <th>HTML</th>
      <th>JavaScript</th>
      <th>jQuery</th>
      <th>PHP</th>
      <th>Make an Interactive Website</th>
      <th>Ruby</th>
      <th>Score</th>
      <th>Comment</th>
      <!--<th>Extras</th>-->
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody id="links">
    <%= render @links %>
  </tbody>
</table>
<div class="ajax-progress"></div>
</div>


<br>

<!--<%= link_to 'New Link', new_link_path %>-->

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/review.js.erb
//$('.table').fadeOut();
//$('.table tr').each(function(index) { $(this).delay(200*index).fadeOut(); })
$('.table tbody tr').fadeOut(100, function() {
            $(this).remove();
})

$("<%= escape_javascript(render @links) %>").hide().each(function(index) {
    $(this).delay(300*index).fadeIn().appendTo("#links");
});

$('#review').button('reset');
$(".ajax-progress").hide();
//$('#review').prop('disabled',false);
    

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @link.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @link.comment %>
</p>

<p>
  <strong>Score:</strong>
  <%= @link.score %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>